
package br.ufg.si.ad.matematica.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Matematica", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Matematica {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "somar", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/", className = "br.ufg.si.ad.matematica.webservices.Somar")
    @ResponseWrapper(localName = "somarResponse", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/", className = "br.ufg.si.ad.matematica.webservices.SomarResponse")
    @Action(input = "http://operacoes.matematica.ad.si.ufg.br/Matematica/somarRequest", output = "http://operacoes.matematica.ad.si.ufg.br/Matematica/somarResponse")
    public double somar(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtrair", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/", className = "br.ufg.si.ad.matematica.webservices.Subtrair")
    @ResponseWrapper(localName = "subtrairResponse", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/", className = "br.ufg.si.ad.matematica.webservices.SubtrairResponse")
    @Action(input = "http://operacoes.matematica.ad.si.ufg.br/Matematica/subtrairRequest", output = "http://operacoes.matematica.ad.si.ufg.br/Matematica/subtrairResponse")
    public double subtrair(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplicar", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/", className = "br.ufg.si.ad.matematica.webservices.Multiplicar")
    @ResponseWrapper(localName = "multiplicarResponse", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/", className = "br.ufg.si.ad.matematica.webservices.MultiplicarResponse")
    @Action(input = "http://operacoes.matematica.ad.si.ufg.br/Matematica/multiplicarRequest", output = "http://operacoes.matematica.ad.si.ufg.br/Matematica/multiplicarResponse")
    public double multiplicar(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dividir", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/", className = "br.ufg.si.ad.matematica.webservices.Dividir")
    @ResponseWrapper(localName = "dividirResponse", targetNamespace = "http://operacoes.matematica.ad.si.ufg.br/", className = "br.ufg.si.ad.matematica.webservices.DividirResponse")
    @Action(input = "http://operacoes.matematica.ad.si.ufg.br/Matematica/dividirRequest", output = "http://operacoes.matematica.ad.si.ufg.br/Matematica/dividirResponse")
    public double dividir(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
